# Generated by Django 6.0.3 on 2026-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('contacts', models.CharField(max_length=255, verbose_name='Контакты')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('designer', 'Дизайнер'), ('backend', 'Программист Backend'), ('frontend', 'Программист Frontend'), ('fullstack', 'Fullstack-разработчик'), ('manager', 'Менеджер')], default='designer', max_length=20)),
            ],
        ),
    ]
